<?xml version="1.0"?>
<robot name="mrobot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find mrobot_description)/urdf/common_properties.xacro"/>

  <xacro:property name="wheel_radius" value="0.033"/>
  <xacro:property name="wheel_length" value="0.017"/>
  <xacro:property name="base_link_radius" value="0.13"/>
  <xacro:property name="base_link_length" value="0.005"/>
  <xacro:property name="motor_radius" value="0.02"/>
  <xacro:property name="motor_length" value="0.08"/>
  <xacro:property name="motor_x" value="-0.055"/>
  <xacro:property name="motor_y_dist" value="0.150"/>
  <xacro:property name="plate_height" value="0.07"/>

  <link name="base_footprint"/>

  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
      </geometry>
      <origin xyz=" 0 0 0" rpy="0 0 0" />
      <material name="yellow" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
      </geometry>
      <origin xyz=" 0 0 0" rpy="0 0 0" />
    </collision>
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.5" />
    </inertial>
  </link>
  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <xacro:macro name="motor" params="prefix yreflect">
    <link name="${prefix}_motor">
      <visual>
        <geometry>
          <cylinder radius="${motor_radius}" length="${motor_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <material name="gray" />
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${motor_radius}" length="${motor_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="0.1" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
          iyy="0.001" iyz="0.0"
          izz="0.001" />
      </inertial>
    </link>
    <joint name="base_${prefix}_motor_joint" type="fixed">
      <origin xyz="${motor_x} ${motor_y_dist/2*yreflect} 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_motor" />
    </joint>
  </xacro:macro>

  <xacro:macro name="wheel" params="prefix yreflect">
    <xacro:motor prefix="${prefix}" yreflect="${yreflect}"/>

    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <material name="white" />
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="0.01" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
          iyy="0.001" iyz="0.0"
          izz="0.001" />
      </inertial>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <origin xyz="0 ${(motor_length+wheel_length)/2*yreflect} 0" rpy="0 0 0"/>
      <parent link="${prefix}_motor"/>
      <child link="${prefix}_wheel_link"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="left" yreflect="1"/>
  <xacro:wheel prefix="right" yreflect="-1"/>

  <link name="front_caster_link">
    <visual>
      <geometry>
        <sphere radius="${wheel_radius/2}" />
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius/2}" />
      </geometry>
      <origin xyz="0 0 0.01" rpy="${pi/2} 0 0"/>
    </collision>
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.001" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0"
        izz="0.0001" />
    </inertial>
  </link>
  <joint name="front_caster_joint" type="fixed">
    <origin xyz="${base_link_radius-wheel_radius/2} 0 -${wheel_radius/2}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="front_caster_link"/>
  </joint>

  <link name="plate_1_link">
    <visual>
      <geometry>
        <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
      </geometry>
      <origin xyz=" 0 0 0 " rpy="0 0 0" />
      <material name="yellow"/>
    </visual>
  </link>
  <joint name="plate_1_joint" type="fixed">
    <origin xyz="0 0 ${plate_height}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="plate_1_link"/>
  </joint>
</robot>
