<?xml version="1.0"?>
<robot name="mrobot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find mrobot_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find mrobot_description)/urdf/inertia.urdf.xacro"/>

  <xacro:property name="wheel_radius" value="0.033"/>
  <xacro:property name="wheel_height" value="0.017"/>
  <xacro:property name="wheel_mass"   value="0.1" />
  <xacro:property name="base_link_radius" value="0.13"/>
  <xacro:property name="base_link_length" value="0.005"/>
  <xacro:property name="base_mass"        value="0.5" />
  <xacro:property name="motor_x" value="-0.05"/>
  <xacro:property name="caster_radius"         value="0.016" />
  <xacro:property name="caster_joint_origin_x" value="-0.12" />
  <xacro:property name="caster_mass"           value="0.01" />
  <xacro:property name="plate_height" value="0.07"/>
  <xacro:property name="plate_mass"   value="0.05"/>
  <xacro:property name="standoff_x" value="0.12"/>
  <xacro:property name="standoff_y" value="0.10"/>

  <link name="base_footprint"/>

  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
      </geometry>
      <origin xyz=" 0 0 0" rpy="0 0 0" />
      <material name="yellow" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
      </geometry>
      <origin xyz=" 0 0 0" rpy="0 0 0" />
    </collision>
    <inertial>
      <origin xyz="0 0 0" />
      <xacro:cylinder_inertia m="${base_mass}" r="${base_link_radius}" h="${base_link_length}"/>
    </inertial>
  </link>
  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <xacro:macro name="wheel" params="prefix yreflect">
    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_height}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <material name="white" />
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_height}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_height}"/>
      </inertial>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <origin xyz="${motor_x} ${base_link_radius*yreflect} 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="left" yreflect="1"/>
  <xacro:wheel prefix="right" yreflect="-1"/>

  <xacro:macro name="caster" params="fb xreflect">
    <link name="${fb}_caster_link">
      <visual>
        <geometry>
          <sphere radius="${caster_radius}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="black" />
      </visual>
      <collision>
        <geometry>
          <sphere radius="${caster_radius}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <xacro:sphere_inertia m="${caster_mass}" r="${caster_radius}"/>
      </inertial>
    </link>
    <joint name="{fb}_caster_joint" type="fixed">
      <origin xyz="${caster_joint_origin_x*xreflect} 0 ${-caster_radius}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="${fb}_caster_link"/>
    </joint>
  </xacro:macro>

  <xacro:caster fb="front" xreflect="-1"/>

  <xacro:macro name="mrobot_standoff_2in" params="parent number x_loc y_loc z_loc">
    <link name="standoff_2in_${number}_link">
      <visual>
        <geometry>
          <box size="0.01 0.01 0.07" />
        </geometry>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <material name="black2">
          <color rgba="0.16 0.17 0.15 0.9"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="0.01 0.01 0.07" />
        </geometry>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="0.001" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001" />
      </inertial>
    </link>
    <joint name="standoff_2in_${number}_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="standoff_2in_${number}_link" />
    </joint>
  </xacro:macro>

  <xacro:macro name="plate" params="num parent">
    <link name="plate_${num}_link">
      <visual>
        <geometry>
          <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <material name="yellow"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <xacro:cylinder_inertia m="0.1" r="${base_link_radius}" h="${base_link_length}"/>
      </inertial>
    </link>
    <joint name="plate_${num}_joint" type="fixed">
      <origin xyz="0 0 ${plate_height}" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child link="plate_${num}_link"/>
    </joint>
  </xacro:macro>

  <xacro:mrobot_standoff_2in parent="base_link" number="1" x_loc="-${standoff_x/2 + 0.03}" y_loc="-${standoff_y - 0.03}" z_loc="${plate_height/2}"/>
  <xacro:mrobot_standoff_2in parent="base_link" number="2" x_loc="-${standoff_x/2 + 0.03}" y_loc="${standoff_y - 0.03}" z_loc="${plate_height/2}"/>
  <xacro:mrobot_standoff_2in parent="base_link" number="3" x_loc="${standoff_x/2}" y_loc="-${standoff_y}" z_loc="${plate_height/2}"/>
  <xacro:mrobot_standoff_2in parent="base_link" number="4" x_loc="${standoff_x/2}" y_loc="${standoff_y}" z_loc="${plate_height/2}"/>

  <xacro:plate num="1" parent="base_link"/>

  <xacro:mrobot_standoff_2in parent="standoff_2in_1_link" number="5" x_loc="0" y_loc="0" z_loc="${plate_height}"/>
  <xacro:mrobot_standoff_2in parent="standoff_2in_2_link" number="6" x_loc="0" y_loc="0" z_loc="${plate_height}"/>
  <xacro:mrobot_standoff_2in parent="standoff_2in_3_link" number="7" x_loc="0" y_loc="0" z_loc="${plate_height}"/>
  <xacro:mrobot_standoff_2in parent="standoff_2in_4_link" number="8" x_loc="0" y_loc="0" z_loc="${plate_height}"/>

  <xacro:plate num="2" parent="plate_1_link"/>

</robot>
